avalanche_daemon_dynamic_public_ip: ifconfigme
avalanche_daemon_http_host: localhost
# This variable is ignored, if avalanche_daemon_dynamic_public_ip is not false
avalanche_daemon_public_ip: "{{ ansible_facts.default_ipv4.address }}"
avalanche_daemon_service_name: avalanchego
log_level: info
