- name: Configure Axia service
  become: true
  template:
    src: axia.service
    dest: "/etc/systemd/system/{{ axia_daemon_service_name }}.service"
    owner: root
    group: root
    mode: u=rw,go=r
  notify:
    - Reload systemd
    - Restart Axia service

- name: Enable Axia service
  become: true
  systemd:
    name: "{{ axia_daemon_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
  notify:
    - Restart Axia service
