evm_binary: "{{ repo_folder }}/build/plugins/evm"
repo_folder: "~{{ ansible_facts.user_id }}/go/src/github.com/sankar-boro/coreth"
repo_name: axia-systems/coreth
repo_url: https://github.com/{{ repo_name }}
repo_branch: dev
