- name: Reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: Restart Avalanche service
  become: true
  service:
    name: "{{ avalanche_daemon_service_name }}"
    state: restarted
