- name: Create staking key
  become: true
  openssl_privatekey:
    path: "{{ avalanche_daemon_staking_tls_key }}"
    size: 4096
    backup: true
    owner: "{{ avalanche_daemon_user }}"
    group: "{{ avalanche_daemon_group }}"
    mode: u=rw,go=

# This CSR isn't used at all by avlanchego. It's a required step when creating
# a certificate with Ansible, even a self signed one. Leaving the CSR in place
# (rather than deleting it) keeps the role idempotent.
- name: Create staking certificate signing request
  become: true
  openssl_csr:
    path: "{{ avalanche_daemon_staking_tls_csr }}"
    basic_constraints:
      - "CA:FALSE"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - dataEncipherment
    key_usage_critical: true
    privatekey_path: "{{ avalanche_daemon_staking_tls_key }}"
    use_common_name_for_san: false
    owner: "{{ avalanche_daemon_user }}"
    group: "{{ avalanche_daemon_group }}"
    mode: u=rw,go=r

# These parameters in this role were arrived at by inspecting an certificate
# that was generated by avlanchego. There is one intentional difference.
# The role generates certificates valid for the Ansible default of 10 years.
# avlanchego generates them valid for 100 years. By using Ansible's default
# (rather than overriding it) the role can be kept idempotent.
- name: Create staking certificate
  become: true
  openssl_certificate:
    path: "{{ avalanche_daemon_staking_tls_cert }}"
    backup: true
    csr_path: "{{ avalanche_daemon_staking_tls_csr }}"
    privatekey_path: "{{ avalanche_daemon_staking_tls_key }}"
    provider: selfsigned
    owner: "{{ avalanche_daemon_user }}"
    group: "{{ avalanche_daemon_group }}"
    mode: u=rw,go=r
