#!/usr/bin/env ansible-playbook
---
- name: Configure Avalanche service
  hosts: avalanche_nodes
  roles:
    - name: avalanche_download
    - name: avalanche_user
    - name: avalanche_install
    - name: avalanche_staker
    - name: avalanche_service
